[package]
name = "hello"
version = "1.0.0"
authors = ["Pavel Voronkin <pvoronkin@gridgain.com>"]
edition = "2018"

[dependencies]
postgres = "0.15.2"
hyper = "0.12"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"

